Release/1.4.0
ISGNeuroTeam/postprocessing_sdk pull request #13
Opened 2023-10-24 08:02 UTC by NikitaSerditov

2023-10-24 17:28 UTC, azenkov-ISG requested changes

2023-10-24 17:28 UTC, azenkov-ISG commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Dockerfile
> +RUN pip install --no-cache-dir  -r requirements.txt
файла не существует

2023-10-24 17:28 UTC, azenkov-ISG commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Makefile
> +	test:
test: c табом лишний не работает так

2023-10-24 17:28 UTC, azenkov-ISG commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Dockerfile
> +COPY requirements.txt /app/requirements.txt
нет такого файла

2023-10-24 17:28 UTC, azenkov-ISG commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/tests/test_{{command_name}}.py
> +from hypothesis import given, strategies as st
Где этот импорт используется ?

2023-10-24 17:28 UTC, azenkov-ISG commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Dockerfile
> +ENTRYPOINT ["pytest"]
pytest не устанавливается в докер файле

2023-10-24 17:28 UTC, azenkov-ISG commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Makefile
> +	docker build --progress=plain --no-cache -t pp_cmd_{{command_name}}_test . && docker run -it pp_cmd_{{command_name}}_test
Зачем опция --no-cache при каждом запуске билдится все заново. Лучше в имя образа добавить версию команды. Как то так -t pp_cmd_{{command_name}}_test:0.0.1
 Не надо копировать код команды  в докер файлe (COPY . /app) лучше монтировать при запуске (опция -v ). Так один и тот же образ будет использоваться для разных команд и не будет по сто раз билдится

2023-10-25 07:49 UTC, NikitaSerditov commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Dockerfile
> +RUN pip install --no-cache-dir  -r requirements.txt
Добавил

2023-10-25 07:49 UTC, NikitaSerditov commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Dockerfile
> +COPY requirements.txt /app/requirements.txt
Добавил

2023-10-25 07:49 UTC, NikitaSerditov commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Dockerfile
> +ENTRYPOINT ["pytest"]
Теперь установится

2023-10-25 07:50 UTC, NikitaSerditov commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/tests/test_{{command_name}}.py
> +from hypothesis import given, strategies as st
Убрал в комментарий. Вообще, потенциально, используется в тестах, уменьшает их количество.

2023-10-25 07:50 UTC, NikitaSerditov commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Makefile
> +	test:
Убрал.

2023-10-25 11:13 UTC, NikitaSerditov commented on postprocessing_sdk/templates/pp_cmd_{{command_name}}/Makefile
> +	docker build --progress=plain --no-cache -t pp_cmd_{{command_name}}_test . && docker run -it pp_cmd_{{command_name}}_test
Я не понимаю как во время сборки образа я буду обращаться к директории которую ещё не скоприовал в образ, а лишь прикручу в виде volume на этапе запуска контейнера.

--no-cache убрал. Образ не буду монтировать.

2023-10-25 11:13 UTC, NikitaSerditov commented
Переделал.

2023-10-25 11:13 UTC, closed without merging